version: '3.8'

services:
  db:
    image: postgres:13
    container_name: my_database
    environment:
      POSTGRES_DB: next-calculator
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: my_application
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/next-calculator?schema=public
      - JWT_SECRET=your-secure-jwt-secret-key
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  db_data:
